using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Palink.Tools.System.Mime;

/// <summary>
/// DefaultMimeItems
/// </summary>
public static class DefaultMimeItems
{
    /// <summary>
    /// Items
    /// </summary>
    public static ReadOnlyCollection<MimeMappingItem> Items = new List<MimeMappingItem>
    {
        new (){Extension = "spl", MimeType = "application/futuresplash"},
        new (){Extension = "hta", MimeType = "application/hta"},
        new (){Extension = "acx", MimeType = "application/internet-property-stream"},
        new (){Extension = "axs", MimeType = "application/olescript"},
        new (){Extension = "prf", MimeType = "application/pics-rules"},
        new (){Extension = "p10", MimeType = "application/pkcs10"},
        new (){Extension = "crl", MimeType = "application/pkix-crl"},
        new (){Extension = "setpay", MimeType = "application/set-payment-initiation"},
        new (){Extension = "setreg", MimeType = "application/set-registration-initiation"},
        new (){Extension = "msg", MimeType = "application/vnd.ms-outlook"},
        new (){Extension = "sst", MimeType = "application/vnd.ms-pkicertstore"},
        new (){Extension = "cat", MimeType = "application/vnd.ms-pkiseccat"},
        new (){Extension = "stl", MimeType = "application/vnd.ms-pkistl"},
        new (){Extension = "mpp", MimeType = "application/vnd.ms-project"},
        new (){Extension = "wcm", MimeType = "application/vnd.ms-works"},
        new (){Extension = "wdb", MimeType = "application/vnd.ms-works"},
        new (){Extension = "wks", MimeType = "application/vnd.ms-works"},
        new (){Extension = "wps", MimeType = "application/vnd.ms-works"},
        new (){Extension = "hlp", MimeType = "application/winhlp"},
        new (){Extension = "tgz", MimeType = "application/x-compressed"},
        new (){Extension = "dcr", MimeType = "application/x-director"},
        new (){Extension = "dir", MimeType = "application/x-director"},
        new (){Extension = "dxr", MimeType = "application/x-director"},
        new (){Extension = "ins", MimeType = "application/x-internet-signup"},
        new (){Extension = "isp", MimeType = "application/x-internet-signup"},
        new (){Extension = "iii", MimeType = "application/x-iphone"},
        new (){Extension = "json", MimeType = "application/json"},
        new (){Extension = "mdb", MimeType = "application/x-msaccess"},
        new (){Extension = "crd", MimeType = "application/x-mscardfile"},
        new (){Extension = "clp", MimeType = "application/x-msclip"},
        new (){Extension = "dll", MimeType = "application/x-msdownload"},
        new (){Extension = "m13", MimeType = "application/x-msmediaview"},
        new (){Extension = "m14", MimeType = "application/x-msmediaview"},
        new (){Extension = "mvb", MimeType = "application/x-msmediaview"},
        new (){Extension = "wmf", MimeType = "application/x-msmetafile"},
        new (){Extension = "mny", MimeType = "application/x-msmoney"},
        new (){Extension = "pub", MimeType = "application/x-mspublisher"},
        new (){Extension = "scd", MimeType = "application/x-msschedule"},
        new (){Extension = "trm", MimeType = "application/x-msterminal"},
        new (){Extension = "wri", MimeType = "application/x-mswrite"},
        new (){Extension = "pma", MimeType = "application/x-perfmon"},
        new (){Extension = "pmc", MimeType = "application/x-perfmon"},
        new (){Extension = "pml", MimeType = "application/x-perfmon"},
        new (){Extension = "pmr", MimeType = "application/x-perfmon"},
        new (){Extension = "pmw", MimeType = "application/x-perfmon"},
        new (){Extension = "p12", MimeType = "application/x-pkcs12"},
        new (){Extension = "pfx", MimeType = "application/x-pkcs12"},
        new (){Extension = "p7b", MimeType = "application/x-pkcs7-certificates"},
        new (){Extension = "p7r", MimeType = "application/x-pkcs7-certreqresp"},
        new (){Extension = "p7c", MimeType = "application/x-pkcs7-mime"},
        new (){Extension = "p7m", MimeType = "application/x-pkcs7-mime"},
        new (){Extension = "p7s", MimeType = "application/x-pkcs7-signature"},
        new (){Extension = "pko", MimeType = "application/ynd.ms-pkipko"},
        new (){Extension = "rmi", MimeType = "audio/mid"},
        new (){Extension = "mp3", MimeType = "audio/mpeg"},
        new (){Extension = "ra", MimeType = "audio/x-pn-realaudio"},
        new (){Extension = "ram", MimeType = "audio/x-pn-realaudio"},
        new (){Extension = "cod", MimeType = "image/cis-cod"},
        new (){Extension = "jfif", MimeType = "image/pipeg"},
        new (){Extension = "ico", MimeType = "image/x-icon"},
        new (){Extension = "mht", MimeType = "message/rfc822"},
        new (){Extension = "mhtml", MimeType = "message/rfc822"},
        new (){Extension = "nws", MimeType = "message/rfc822"},
        new (){Extension = "323", MimeType = "text/h323"},
        new (){Extension = "uls", MimeType = "text/iuls"},
        new (){Extension = "sct", MimeType = "text/scriptlet"},
        new (){Extension = "htt", MimeType = "text/webviewhtml"},
        new (){Extension = "vcf", MimeType = "text/x-vcard"},
        new (){Extension = "lsf", MimeType = "video/x-la-asf"},
        new (){Extension = "lsx", MimeType = "video/x-la-asf"},
        new (){Extension = "3gp", MimeType = "video/3gpp"},
        new (){Extension = "aab", MimeType = "application/x-authoware-bin"},
        new (){Extension = "aam", MimeType = "application/x-authoware-map"},
        new (){Extension = "aas", MimeType = "application/x-authoware-seg"},
        new (){Extension = "als", MimeType = "audio/X-Alpha5"},
        new (){Extension = "amc", MimeType = "application/x-mpeg"},
        new (){Extension = "asd", MimeType = "application/astound"},
        new (){Extension = "asn", MimeType = "application/astound"},
        new (){Extension = "asp", MimeType = "application/x-asap"},
        new (){Extension = "awb", MimeType = "audio/amr-wb"},
        new (){Extension = "bld", MimeType = "application/bld"},
        new (){Extension = "bld2", MimeType = "application/bld2"},
        new (){Extension = "bz2", MimeType = "application/x-bzip2"},
        new (){Extension = "cal", MimeType = "image/x-cals"},
        new (){Extension = "ccn", MimeType = "application/x-cnc"},
        new (){Extension = "cco", MimeType = "application/x-cocoa"},
        new (){Extension = "cgi", MimeType = "magnus-internal/cgi"},
        new (){Extension = "chat", MimeType = "application/x-chat"},
        new (){Extension = "cmx", MimeType = "application/x-cmx"},
        new (){Extension = "co", MimeType = "application/x-cult3d-object"},
        new (){Extension = "cpt", MimeType = "application/mac-compactpro"},
        new (){Extension = "csm", MimeType = "chemical/x-csml"},
        new (){Extension = "csml", MimeType = "chemical/x-csml"},
        new (){Extension = "dcm", MimeType = "x-lml/x-evm"},
        new (){Extension = "dcx", MimeType = "image/x-dcx"},
        new (){Extension = "dot", MimeType = "application/x-dot"},
        new (){Extension = "dwf", MimeType = "drawing/x-dwf"},
        new (){Extension = "dwg", MimeType = "application/x-autocad"},
        new (){Extension = "dxf", MimeType = "application/x-autocad"},
        new (){Extension = "ebk", MimeType = "application/x-expandedbook"},
        new (){Extension = "emb", MimeType = "chemical/x-embl-dl-nucleotide"},
        new (){Extension = "embl", MimeType = "chemical/x-embl-dl-nucleotide"},
        new (){Extension = "eri", MimeType = "image/x-eri"},
        new (){Extension = "es", MimeType = "audio/echospeech"},
        new (){Extension = "esl", MimeType = "audio/echospeech"},
        new (){Extension = "etc", MimeType = "application/x-earthtime"},
        new (){Extension = "evm", MimeType = "x-lml/x-evm"},
        new (){Extension = "evy", MimeType = "application/x-envoy"},
        new (){Extension = "fh4", MimeType = "image/x-freehand"},
        new (){Extension = "fh5", MimeType = "image/x-freehand"},
        new (){Extension = "fhc", MimeType = "image/x-freehand"},
        new (){Extension = "fif", MimeType = "image/fif"},
        new (){Extension = "fm", MimeType = "application/x-maker"},
        new (){Extension = "fpx", MimeType = "image/x-fpx"},
        new (){Extension = "fvi", MimeType = "video/isivideo"},
        new (){Extension = "gau", MimeType = "chemical/x-gaussian-input"},
        new (){Extension = "gca", MimeType = "application/x-gca-compressed"},
        new (){Extension = "gdb", MimeType = "x-lml/x-gdb"},
        new (){Extension = "gps", MimeType = "application/x-gps"},
        new (){Extension = "hdm", MimeType = "text/x-hdml"},
        new (){Extension = "hdml", MimeType = "text/x-hdml"},
        new (){Extension = "ice", MimeType = "x-conference/x-cooltalk"},
        new (){Extension = "ifs", MimeType = "image/ifs"},
        new (){Extension = "imy", MimeType = "audio/melody"},
        new (){Extension = "ips", MimeType = "application/x-ip******"},
        new (){Extension = "ipx", MimeType = "application/x-ipix"},
        new (){Extension = "it", MimeType = "audio/x-mod"},
        new (){Extension = "itz", MimeType = "audio/x-mod"},
        new (){Extension = "ivr", MimeType = "i-world/i-vrml"},
        new (){Extension = "j2k", MimeType = "image/j2k"},
        new (){Extension = "jam", MimeType = "application/x-jam"},
        new (){Extension = "jwc", MimeType = "application/jwc"},
        new (){Extension = "kjx", MimeType = "application/x-kjx"},
        new (){Extension = "lak", MimeType = "x-lml/x-lak"},
        new (){Extension = "lcc", MimeType = "application/fastman"},
        new (){Extension = "lcl", MimeType = "application/x-digitalloca"},
        new (){Extension = "lcr", MimeType = "application/x-digitalloca"},
        new (){Extension = "lgh", MimeType = "application/lgh"},
        new (){Extension = "lml", MimeType = "x-lml/x-lml"},
        new (){Extension = "lmlpack", MimeType = "x-lml/x-lmlpack"},
        new (){Extension = "lzh", MimeType = "application/x-lzh"},
        new (){Extension = "m15", MimeType = "audio/x-mod"},
        new (){Extension = "ma1", MimeType = "audio/ma1"},
        new (){Extension = "ma2", MimeType = "audio/ma2"},
        new (){Extension = "ma3", MimeType = "audio/ma3"},
        new (){Extension = "ma5", MimeType = "audio/ma5"},
        new (){Extension = "map", MimeType = "magnus-internal/imagemap"},
        new (){Extension = "mbd", MimeType = "application/mbedlet"},
        new (){Extension = "mct", MimeType = "application/x-mascot"},
        new (){Extension = "mdz", MimeType = "audio/x-mod"},
        new (){Extension = "mel", MimeType = "text/x-vmel"},
        new (){Extension = "mid", MimeType = "audio/midi"},
        new (){Extension = "midi", MimeType = "audio/midi"},
        new (){Extension = "mil", MimeType = "image/x-cals"},
        new (){Extension = "mio", MimeType = "audio/x-mio"},
        new (){Extension = "mmf", MimeType = "application/x-skt-lbs"},
        new (){Extension = "mng", MimeType = "video/x-mng"},
        new (){Extension = "moc", MimeType = "application/x-mocha"},
        new (){Extension = "mocha", MimeType = "application/x-mocha"},
        new (){Extension = "mod", MimeType = "audio/x-mod"},
        new (){Extension = "mof", MimeType = "application/x-yumekara"},
        new (){Extension = "mol", MimeType = "chemical/x-mdl-molfile"},
        new (){Extension = "mop", MimeType = "chemical/x-mopac-input"},
        new (){Extension = "mpc", MimeType = "application/vnd.mpohun.certificate"},
        new (){Extension = "mpn", MimeType = "application/vnd.mophun.application"},
        new (){Extension = "mps", MimeType = "application/x-mapserver"},
        new (){Extension = "mrl", MimeType = "text/x-mrml"},
        new (){Extension = "mrm", MimeType = "application/x-mrm"},
        new (){Extension = "mts", MimeType = "application/metastream"},
        new (){Extension = "mtx", MimeType = "application/metastream"},
        new (){Extension = "mtz", MimeType = "application/metastream"},
        new (){Extension = "mzv", MimeType = "application/metastream"},
        new (){Extension = "nbmp", MimeType = "image/nbmp"},
        new (){Extension = "ndb", MimeType = "x-lml/x-ndb"},
        new (){Extension = "ndwn", MimeType = "application/ndwn"},
        new (){Extension = "nif", MimeType = "application/x-nif"},
        new (){Extension = "nmz", MimeType = "application/x-scream"},
        new (){Extension = "nokia-op-logo", MimeType = "image/vnd.nok-oplogo-color"},
        new (){Extension = "npx", MimeType = "application/x-netfpx"},
        new (){Extension = "nsnd", MimeType = "audio/nsnd"},
        new (){Extension = "nva", MimeType = "application/x-neva1"},
        new (){Extension = "oom", MimeType = "application/x-AtlasMate-Plugin"},
        new (){Extension = "pac", MimeType = "audio/x-pac"},
        new (){Extension = "pae", MimeType = "audio/x-epac"},
        new (){Extension = "pan", MimeType = "application/x-pan"},
        new (){Extension = "pcx", MimeType = "image/x-pcx"},
        new (){Extension = "pda", MimeType = "image/x-pda"},
        new (){Extension = "pdb", MimeType = "chemical/x-pdb"},
        new (){Extension = "pfr", MimeType = "application/font-tdpfr"},
        new (){Extension = "pm", MimeType = "application/x-perl"},
        new (){Extension = "pmd", MimeType = "application/x-pmd"},
        new (){Extension = "pqf", MimeType = "application/x-cprplayer"},
        new (){Extension = "pqi", MimeType = "application/cprplayer"},
        new (){Extension = "prc", MimeType = "application/x-prc"},
        new (){Extension = "proxy", MimeType = "application/x-ns-proxy-autoconfig"},
        new (){Extension = "ptlk", MimeType = "application/listenup"},
        new (){Extension = "pvx", MimeType = "video/x-pv-pvx"},
        new (){Extension = "qcp", MimeType = "audio/vnd.qcelp"},
        new (){Extension = "r3t", MimeType = "text/vnd.rn-realtext3d"},
        new (){Extension = "rar", MimeType = "application/x-rar-compressed"},
        new (){Extension = "rf", MimeType = "image/vnd.rn-realflash"},
        new (){Extension = "rlf", MimeType = "application/x-richlink"},
        new (){Extension = "rmf", MimeType = "audio/x-rmf"},
        new (){Extension = "rnx", MimeType = "application/vnd.rn-realplayer"},
        new (){Extension = "rp", MimeType = "image/vnd.rn-realpix"},
        new (){Extension = "rpm", MimeType = "audio/x-pn-realaudio-plugin"},
        new (){Extension = "rt", MimeType = "text/vnd.rn-realtext"},
        new (){Extension = "rte", MimeType = "x-lml/x-gps"},
        new (){Extension = "rtg", MimeType = "application/metastream"},
        new (){Extension = "rv", MimeType = "video/vnd.rn-realvideo"},
        new (){Extension = "rwc", MimeType = "application/x-rogerwilco"},
        new (){Extension = "s3m", MimeType = "audio/x-mod"},
        new (){Extension = "s3z", MimeType = "audio/x-mod"},
        new (){Extension = "sca", MimeType = "application/x-supercard"},
        new (){Extension = "sdf", MimeType = "application/e-score"},
        new (){Extension = "sgm", MimeType = "text/x-sgml"},
        new (){Extension = "sgml", MimeType = "text/x-sgml"},
        new (){Extension = "shtml", MimeType = "magnus-internal/parsed-html"},
        new (){Extension = "shw", MimeType = "application/presentations"},
        new (){Extension = "si6", MimeType = "image/si6"},
        new (){Extension = "si7", MimeType = "image/vnd.stiwap.sis"},
        new (){Extension = "si9", MimeType = "image/vnd.lgtwap.sis"},
        new (){Extension = "sis", MimeType = "application/vnd.symbian.install"},
        new (){Extension = "skd", MimeType = "application/x-Koan"},
        new (){Extension = "skm", MimeType = "application/x-Koan"},
        new (){Extension = "skp", MimeType = "application/x-Koan"},
        new (){Extension = "skt", MimeType = "application/x-Koan"},
        new (){Extension = "slc", MimeType = "application/x-salsa"},
        new (){Extension = "smd", MimeType = "audio/x-smd"},
        new (){Extension = "smi", MimeType = "application/smil"},
        new (){Extension = "smil", MimeType = "application/smil"},
        new (){Extension = "smp", MimeType = "application/studiom"},
        new (){Extension = "smz", MimeType = "audio/x-smd"},
        new (){Extension = "spc", MimeType = "text/x-speech"},
        new (){Extension = "spr", MimeType = "application/x-sprite"},
        new (){Extension = "sprite", MimeType = "application/x-sprite"},
        new (){Extension = "spt", MimeType = "application/x-spt"},
        new (){Extension = "stk", MimeType = "application/hyperstudio"},
        new (){Extension = "stm", MimeType = "audio/x-mod"},
        new (){Extension = "svf", MimeType = "image/vnd"},
        new (){Extension = "svh", MimeType = "image/svh"},
        new (){Extension = "svr", MimeType = "x-world/x-svr"},
        new (){Extension = "talk", MimeType = "text/x-speech"},
        new (){Extension = "tbp", MimeType = "application/x-timbuktu"},
        new (){Extension = "tbt", MimeType = "application/x-timbuktu"},
        new (){Extension = "thm", MimeType = "application/vnd.eri.thm"},
        new (){Extension = "tki", MimeType = "application/x-tkined"},
        new (){Extension = "tkined", MimeType = "application/x-tkined"},
        new (){Extension = "toc", MimeType = "application/toc"},
        new (){Extension = "toy", MimeType = "image/toy"},
        new (){Extension = "trk", MimeType = "x-lml/x-gps"},
        new (){Extension = "tsi", MimeType = "audio/tsplayer"},
        new (){Extension = "tsp", MimeType = "application/dsptype"},
        new (){Extension = "ttz", MimeType = "application/t-time"},
        new (){Extension = "ult", MimeType = "audio/x-mod"},
        new (){Extension = "uu", MimeType = "application/x-uuencode"},
        new (){Extension = "uue", MimeType = "application/x-uuencode"},
        new (){Extension = "vcd", MimeType = "application/x-cdlink"},
        new (){Extension = "vdo", MimeType = "video/vdo"},
        new (){Extension = "vib", MimeType = "audio/vib"},
        new (){Extension = "viv", MimeType = "video/vivo"},
        new (){Extension = "vivo", MimeType = "video/vivo"},
        new (){Extension = "vmd", MimeType = "application/vocaltec-media-desc"},
        new (){Extension = "vmf", MimeType = "application/vocaltec-media-file"},
        new (){Extension = "vmi", MimeType = "application/x-dreamcast-vms-info"},
        new (){Extension = "vms", MimeType = "application/x-dreamcast-vms"},
        new (){Extension = "vox", MimeType = "audio/voxware"},
        new (){Extension = "vqe", MimeType = "audio/x-twinvq-plugin"},
        new (){Extension = "vqf", MimeType = "audio/x-twinvq"},
        new (){Extension = "vql", MimeType = "audio/x-twinvq"},
        new (){Extension = "vre", MimeType = "x-world/x-vream"},
        new (){Extension = "vrt", MimeType = "x-world/x-vrt"},
        new (){Extension = "vrw", MimeType = "x-world/x-vream"},
        new (){Extension = "vts", MimeType = "workbook/formulaone"},
        new (){Extension = "wax", MimeType = "audio/x-ms-wax"},
        new (){Extension = "web", MimeType = "application/vnd.xara"},
        new (){Extension = "wi", MimeType = "image/wavelet"},
        new (){Extension = "wis", MimeType = "application/x-InstallShield"},
        new (){Extension = "wm", MimeType = "video/x-ms-wm"},
        new (){Extension = "wma", MimeType = "audio/x-ms-wma"},
        new (){Extension = "wmd", MimeType = "application/x-ms-wmd"},
        new (){Extension = "wmx", MimeType = "video/x-ms-wmx"},
        new (){Extension = "wmz", MimeType = "application/x-ms-wmz"},
        new (){Extension = "wpng", MimeType = "image/x-up-wpng"},
        new (){Extension = "wpt", MimeType = "x-lml/x-gps"},
        new (){Extension = "ws", MimeType = "text/vnd.wap.wml******"},
        new (){Extension = "wsc", MimeType = "application/vnd.wap.wml******c"},
        new (){Extension = "wv", MimeType = "video/wavelet"},
        new (){Extension = "wvx", MimeType = "video/x-ms-wvx"},
        new (){Extension = "wxl", MimeType = "application/x-wxl"},
        new (){Extension = "xar", MimeType = "application/vnd.xara"},
        new (){Extension = "xdm", MimeType = "application/x-xdma"},
        new (){Extension = "xdma", MimeType = "application/x-xdma"},
        new (){Extension = "xdw", MimeType = "application/vnd.fujixerox.docuworks"},
        new (){Extension = "xll", MimeType = "application/x-excel"},
        new (){Extension = "xm", MimeType = "audio/x-mod"},
        new (){Extension = "xml", MimeType = "text/xml"},
        new (){Extension = "xmz", MimeType = "audio/x-mod"},
        new (){Extension = "xpi", MimeType = "application/x-xpinstall"},
        new (){Extension = "xsit", MimeType = "text/xml"},
        new (){Extension = "xsl", MimeType = "text/xml"},
        new (){Extension = "xul", MimeType = "text/xul"},
        new (){Extension = "xyz", MimeType = "chemical/x-pdb"},
        new (){Extension = "yz1", MimeType = "application/x-yz1"},
        new (){Extension = "zac", MimeType = "application/x-zaurus-zac"},
        new (){Extension = "abs", MimeType = "audio/x-mpeg"},
        new (){Extension = "ai", MimeType = "application/postscript"},
        new (){Extension = "aif", MimeType = "audio/x-aiff"},
        new (){Extension = "aifc", MimeType = "audio/x-aiff"},
        new (){Extension = "aiff", MimeType = "audio/x-aiff"},
        new (){Extension = "aim", MimeType = "application/x-aim"},
        new (){Extension = "art", MimeType = "image/x-jg"},
        new (){Extension = "asf", MimeType = "video/x-ms-asf"},
        new (){Extension = "asx", MimeType = "video/x-ms-asf"},
        new (){Extension = "au", MimeType = "audio/basic"},
        new (){Extension = "avi", MimeType = "video/x-msvideo"},
        new (){Extension = "avx", MimeType = "video/x-rad-screenplay"},
        new (){Extension = "bcpio", MimeType = "application/x-bcpio"},
        new (){Extension = "bin", MimeType = "application/octet-stream"},
        new (){Extension = "bmp", MimeType = "image/bmp"},
        new (){Extension = "webp", MimeType = "image/webp"},
        new (){Extension = "body", MimeType = "text/html"},
        new (){Extension = "cdf", MimeType = "application/x-cdf"},
        new (){Extension = "cer", MimeType = "application/x-x509-ca-cert"},
        new (){Extension = "class", MimeType = "application/java"},
        new (){Extension = "cpio", MimeType = "application/x-cpio"},
        new (){Extension = "csh", MimeType = "application/x-csh"},
        new (){Extension = "css", MimeType = "text/css"},
        new (){Extension = "dib", MimeType = "image/bmp"},
        new (){Extension = "doc", MimeType = "application/msword"},
        new (){Extension = "docx", MimeType = "application/msword"},
        new (){Extension = "dtd", MimeType = "application/xml-dtd"},
        new (){Extension = "dv", MimeType = "video/x-dv"},
        new (){Extension = "dvi", MimeType = "application/x-dvi"},
        new (){Extension = "eps", MimeType = "application/postscript"},
        new (){Extension = "etx", MimeType = "text/x-setext"},
        new (){Extension = "exe", MimeType = "application/octet-stream"},
        new (){Extension = "gif", MimeType = "image/gif"},
        new (){Extension = "gtar", MimeType = "application/x-gtar"},
        new (){Extension = "gz", MimeType = "application/x-gzip"},
        new (){Extension = "ogv", MimeType = "video/ogg"},
        new (){Extension = "oga", MimeType = "audio/ogg"},
        new (){Extension = "ogg", MimeType = "audio/ogg"},
        new (){Extension = "hdf", MimeType = "application/x-hdf"},
        new (){Extension = "htc", MimeType = "text/x-component"},
        new (){Extension = "htm", MimeType = "text/html"},
        new (){Extension = "html", MimeType = "text/html"},
        new (){Extension = "hqx", MimeType = "application/mac-binhex40"},
        new (){Extension = "ief", MimeType = "image/ief"},
        new (){Extension = "jad", MimeType = "text/vnd.sun.j2me.app-descriptor"},
        new (){Extension = "jar", MimeType = "application/java-archive"},
        new (){Extension = "java", MimeType = "text/plain"},
        new (){Extension = "jnlp", MimeType = "application/x-java-jnlp-file"},
        new (){Extension = "jpe", MimeType = "image/jpeg"},
        new (){Extension = "jpeg", MimeType = "image/jpeg"},
        new (){Extension = "jpg", MimeType = "image/jpeg"},
        new (){Extension = "js", MimeType = "text/javascript"},
        new (){Extension = "jsx", MimeType = "text/javascript"},
        new (){Extension = "jsf", MimeType = "text/plain"},
        new (){Extension = "jspf", MimeType = "text/plain"},
        new (){Extension = "kar", MimeType = "audio/x-midi"},
        new (){Extension = "latex", MimeType = "application/x-latex"},
        new (){Extension = "m3u", MimeType = "audio/x-mpegurl"},
        new (){Extension = "mac", MimeType = "image/x-macpaint"},
        new (){Extension = "man", MimeType = "application/x-troff-man"},
        new (){Extension = "mathml", MimeType = "application/mathml+xml"},
        new (){Extension = "me", MimeType = "application/x-troff-me"},
        new (){Extension = "mif", MimeType = "application/x-mif"},
        new (){Extension = "mov", MimeType = "video/quicktime"},
        new (){Extension = "movie", MimeType = "video/x-sgi-movie"},
        new (){Extension = "mp1", MimeType = "audio/x-mpeg"},
        new (){Extension = "mp2", MimeType = "audio/x-mpeg"},
        new (){Extension = "mp4", MimeType = "video/mp4"},
        new (){Extension = "mpa", MimeType = "audio/x-mpeg"},
        new (){Extension = "mpe", MimeType = "video/mpeg"},
        new (){Extension = "mpeg", MimeType = "video/mpeg"},
        new (){Extension = "mpega", MimeType = "audio/x-mpeg"},
        new (){Extension = "mpg", MimeType = "video/mpeg"},
        new (){Extension = "mpv2", MimeType = "video/mpeg2"},
        new (){Extension = "ms", MimeType = "application/x-wais-source"},
        new (){Extension = "nc", MimeType = "application/x-netcdf"},
        new (){Extension = "oda", MimeType = "application/oda"},
        
        //<!-- OpenDocument Database -->
        new (){Extension = "odb", MimeType = "application/vnd.oasis.opendocument.database"},
        
        //<!-- OpenDocument Chart -->
        new (){Extension = "odc", MimeType = "application/vnd.oasis.opendocument.chart"},

        //<!-- OpenDocument Formula -->
        new (){Extension = "odf", MimeType = "application/vnd.oasis.opendocument.formula"},

        //<!-- OpenDocument Drawing -->
        new (){Extension = "odg", MimeType = "application/vnd.oasis.opendocument.graphics"},

        //<!-- OpenDocument Image -->
        new (){Extension = "odi", MimeType = "application/vnd.oasis.opendocument.image"},

        //<!-- OpenDocument Master Document -->
        new (){Extension = "odm", MimeType = "application/vnd.oasis.opendocument.text-master"},

        //<!-- OpenDocument Presentation -->
        new (){Extension = "odp", MimeType = "application/vnd.oasis.opendocument.presentation"},

        //<!-- OpenDocument Spreadsheet -->
        new (){Extension = "ods", MimeType = "application/vnd.oasis.opendocument.spreadsheet"},

        //<!-- OpenDocument Text -->
        new (){Extension = "odt", MimeType = "application/vnd.oasis.opendocument.text"},

        //<!-- OpenDocument Drawing Template -->
        new (){Extension = "otg ", MimeType = "application/vnd.oasis.opendocument.graphics-template"},

        //<!-- HTML Document Template -->
        new (){Extension = "oth", MimeType = "application/vnd.oasis.opendocument.text-web"},

        //<!-- OpenDocument Presentation Template -->
        new (){Extension = "otp", MimeType = "application/vnd.oasis.opendocument.presentation-template"},

        //<!-- OpenDocument Spreadsheet Template -->
        new (){Extension = "ots", MimeType = "application/vnd.oasis.opendocument.spreadsheet-template "},

        //<!-- OpenDocument Text Template -->
        new (){Extension = "ott", MimeType = "application/vnd.oasis.opendocument.text-template"},
        new (){Extension = "pbm", MimeType = "image/x-portable-bitmap"},
        new (){Extension = "pct", MimeType = "image/pict"},
        new (){Extension = "pdf", MimeType = "application/pdf"},
        new (){Extension = "pgm", MimeType = "image/x-portable-graymap"},
        new (){Extension = "pic", MimeType = "image/pict"},
        new (){Extension = "pict", MimeType = "image/pict"},
        new (){Extension = "pls", MimeType = "audio/x-scpls"},
        new (){Extension = "png", MimeType = "image/png"},
        new (){Extension = "pnm", MimeType = "image/x-portable-anymap"},
        new (){Extension = "pnt", MimeType = "image/x-macpaint"},
        new (){Extension = "ppm", MimeType = "image/x-portable-pixmap"},
        new (){Extension = "ppt", MimeType = "application/vnd.ms-powerpoint"},
        new (){Extension = "pptx", MimeType = "application/vnd.ms-powerpoint"},
        new (){Extension = "pps", MimeType = "application/vnd.ms-powerpoint"},
        new (){Extension = "ps", MimeType = "application/postscript"},
        new (){Extension = "psd", MimeType = "image/x-photoshop"},
        new (){Extension = "qt", MimeType = "video/quicktime"},
        new (){Extension = "qti", MimeType = "image/x-quicktime"},
        new (){Extension = "qtif", MimeType = "image/x-quicktime"},
        new (){Extension = "ras", MimeType = "image/x-cmu-raster"},
        new (){Extension = "rdf", MimeType = "application/rdf+xml"},
        new (){Extension = "reg", MimeType = "application/octet-stream"},
        new (){Extension = "rgb", MimeType = "image/x-rgb"},
        new (){Extension = "rm", MimeType = "application/vnd.rn-realmedia"},
        new (){Extension = "roff", MimeType = "application/x-troff"},
        new (){Extension = "rtf", MimeType = "application/rtf"},
        new (){Extension = "rtx", MimeType = "text/richtext"},
        new (){Extension = "sh", MimeType = "application/x-sh"},
        new (){Extension = "shar", MimeType = "application/x-shar"},
        new (){Extension = "smf", MimeType = "audio/x-midi"},
        new (){Extension = "sit", MimeType = "application/x-stuffit"},
        new (){Extension = "snd", MimeType = "audio/basic"},
        new (){Extension = "src", MimeType = "application/x-wais-source"},
        new (){Extension = "sv4cpio", MimeType = "application/x-sv4cpio"},
        new (){Extension = "sv4crc", MimeType = "application/x-sv4crc"},
        new (){Extension = "svg", MimeType = "image/svg+xml"},
        new (){Extension = "svgz", MimeType = "image/svg+xml"},
        new (){Extension = "swf", MimeType = "application/x-shockwave-flash"},
        new (){Extension = "t", MimeType = "application/x-troff"},
        new (){Extension = "tar", MimeType = "application/x-tar"},
        new (){Extension = "tcl", MimeType = "application/x-tcl"},
        new (){Extension = "tex", MimeType = "application/x-tex"},
        new (){Extension = "texi", MimeType = "application/x-texinfo"},
        new (){Extension = "texinfo", MimeType = "application/x-texinfo"},
        new (){Extension = "tif", MimeType = "image/tiff"},
        new (){Extension = "tiff", MimeType = "image/tiff"},
        new (){Extension = "torrent", MimeType = "application/octet-stream"},
        new (){Extension = "tr", MimeType = "application/x-troff"},
        new (){Extension = "tsv", MimeType = "text/tab-separated-values"},
        new (){Extension = "ttf", MimeType = "application/x-font-ttf"},
        new (){Extension = "txt", MimeType = "text/plain"},
        new (){Extension = "cs", MimeType = "text/plain"},
        new (){Extension = "c", MimeType = "text/plain"},
        new (){Extension = "cpp", MimeType = "text/plain"},
        new (){Extension = "ulw", MimeType = "audio/basic"},
        new (){Extension = "ustar", MimeType = "application/x-ustar"},
        new (){Extension = "vxml", MimeType = "application/voicexml+xml"},
        new (){Extension = "xbm", MimeType = "image/x-xbitmap"},
        new (){Extension = "xht", MimeType = "application/xhtml+xml"},
        new (){Extension = "xhtml", MimeType = "application/xhtml+xml"},
        new (){Extension = "xls", MimeType = "application/vnd.ms-excel"},
        new (){Extension = "xlsx", MimeType = "application/vnd.ms-excel"},
        new (){Extension = "xpm", MimeType = "image/x-xpixmap"},
        new (){Extension = "xslt", MimeType = "application/xslt+xml"},
        new (){Extension = "xwd", MimeType = "image/x-xwindowdump"},
        new (){Extension = "vsd", MimeType = "application/x-visio"},
        new (){Extension = "wav", MimeType = "audio/x-wav"},
        
        //<!-- Wireless Bitmap -->
        new (){Extension = "wbmp", MimeType = "image/vnd.wap.wbmp"},

        //<!-- WML Source -->
        new (){Extension = "wml", MimeType = "text/vnd.wap.wml"},

        //<!-- Compiled WML -->
        new (){Extension = "wmlc", MimeType = "application/vnd.wap.wmlc"},

        //<!-- WML Script Source -->
        new (){Extension = "wmls", MimeType = "text/vnd.wap.wmlscript"},

        //<!-- Compiled WML Script -->
        new (){Extension = "wmlscriptc", MimeType = "application/vnd.wap.wmlscriptc"},
        new (){Extension = "wmv", MimeType = "video/x-ms-wmv"},
        new (){Extension = "woff", MimeType = "font/woff2"},
        new (){Extension = "woff2", MimeType = "font/woff2"},
        new (){Extension = "wrl", MimeType = "x-world/x-vrml"},
        new (){Extension = "wspolicy", MimeType = "application/wspolicy+xml"},
        new (){Extension = "Z", MimeType = "application/x-compress"},
        new (){Extension = "z", MimeType = "application/x-compress"},
        new (){Extension = "zip", MimeType = "application/zip"},
    }.AsReadOnly();
}